---

- hosts: webserver
  become: true
  user: ubuntu
  
  tasks:
  - name: Copying kubernetes deployment file
    copy:
      src: /home/ec2-user/ansible/website-deployment.yml
      dest: /home/ubuntu/website-deployment.yml

  
  - name: Delete deployment if alread exist
    command: kubectl delete deployment/web
    ignore_errors: True
    
  - name: Delete service if alread exist
    command: kubectl delete service/web
    ignore_errors: True
    
  - name: Kubernetes deployment
    command: kubectl apply -f website-deployment.yml

