#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: inverseinfinity/kubernetes_deployment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---
#service
apiVersion: v1
kind: Service

metadata:
  name: web

spec:
  selector:
    app: web

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32020

  type: LoadBalancer

